### ISSUE TITLE
Tensorboard delayed output

### ISSUE THREAD

**Issue by Rauf-Kurbanov** [neuro-inc/cookiecutter-neuro-project#339] opened 2020-01-31 12:39 UTC
Because of the following issue:
https://github.com/tensorflow/tensorboard/issues/867
tensorboard does not immediately flush outputs on GCS.

It is fixes pretty easily by adding `-e GCS_READ_CACHE_MAX_SIZE_MB=0`
I may contribute it myself later

**Comment by YevheniiSemendiak** [comment] 2021-08-20 14:17
not relevant repo, should be in base-image
the issue was resolved in TensorBoard 1.9, we now have [2.5](https://github.com/neuro-inc/neuro-base-environment/blob/66547361fa424e80329a111f6a0199f235557960/requirements/python.txt#L14), closing this issue since the problem is outdated

**Closed by YevheniiSemendiak** 2021-08-20 14:17 UTC
Labels: good first issue, Makefile
